import { create } from 'zustand';

export type Language = 'en' | 'ru' | 'uz';

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    courses: 'Courses',
    grading: 'Assign & Grade',
    assignments: 'Assignments',
    settings: 'Settings',
    goodMorning: 'Good morning,',
    adminOverview: 'Administrator Control Hub',
    teacherOverview: 'Teacher Workspace Overview',
    assistantTeacherOverview: 'Assistant Teacher Support Hub',
    studentOverview: 'Student Overview',
    parentOverview: 'Parent Monitoring Portal',
    pendingTeacherActions: 'Pending Teacher Actions',
    pendingAdminActions: 'Branch Admin System Alerts',
    pendingAssistantActions: 'Lab & Quiz Grading Assistance',
    parentUpdates: 'Child Progress Updates',
    recentActivity: 'Recent Activity',
    activeClasses: 'Active Classes',
    toGrade: 'To Grade',
    avgAttendance: 'Avg Attendance',
    activeCourses: 'Active Courses',
    assignmentsDue: 'Assignments Due',
    completed: 'Completed',
    totalUsers: 'Total Branch Users',
    systemHealth: 'System Health',
    personalProfile: 'Personal Profile',
    notifications: 'Notifications & Alerts',
    toggleTheme: 'Toggle Brand Theme',
    signOut: 'Sign Out',
    activeRole: 'Active App Role Context (5 Roles):',
    adminMode: 'Admin',
    teacherMode: 'Teacher',
    assistantTeacherMode: 'Assistant',
    studentMode: 'Student',
    parentMode: 'Parent',
    language: 'Language / Язык / Tili',
    selectLanguage: 'Select Language',
    profileAlertTitle: 'Personal Profile',
    profileAlertMsg: 'Profile management & credentials configuration.',
    notifAlertTitle: 'Notifications & Alerts',
    notifAlertMsg: 'Push notification preferences & system alerts updated.',
    signOutAlertTitle: 'Sign Out',
    signOutAlertMsg: 'You have been signed out successfully.',
    courseDetails: 'Course Details',
    viewLessons: 'View Lessons & Syllabus',
    maxScore: 'Max Points',
    graded: 'Graded',
    allGraded: 'All Graded',
    publishToStudents: 'Publish to Students',
    createAssignment: 'Create & Publish Assignment',
    title: 'Title',
    course: 'Course',
  },
  ru: {
    dashboard: 'Дашборд',
    courses: 'Курсы',
    grading: 'Проверка и оценки',
    assignments: 'Задания',
    settings: 'Настройки',
    goodMorning: 'Доброе утро,',
    adminOverview: 'Центр управления администратора',
    teacherOverview: 'Обзор преподавателя',
    assistantTeacherOverview: 'Кабинет ассистента преподавателя',
    studentOverview: 'Обзор студента',
    parentOverview: 'Портал родительского контроля',
    pendingTeacherActions: 'Ожидающие действия',
    pendingAdminActions: 'Системные уведомления филиала',
    pendingAssistantActions: 'Помощь в проверке тестов и лабораторных',
    parentUpdates: 'Обновления успеваемости ребенка',
    recentActivity: 'Последние действия',
    activeClasses: 'Активные классы',
    toGrade: 'На проверку',
    avgAttendance: 'Ср. посещаемость',
    activeCourses: 'Активные курсы',
    assignmentsDue: 'Предстоит сдать',
    completed: 'Завершено',
    totalUsers: 'Всего пользователей',
    systemHealth: 'Состояние системы',
    personalProfile: 'Личный профиль',
    notifications: 'Уведомления и оповещения',
    toggleTheme: 'Сменить тему бренда',
    signOut: 'Выйти из системы',
    activeRole: 'Текущая роль в приложении (5 ролей):',
    adminMode: 'Админ',
    teacherMode: 'Учитель',
    assistantTeacherMode: 'Ассистент',
    studentMode: 'Студент',
    parentMode: 'Родитель',
    language: 'Язык / Language / Tili',
    selectLanguage: 'Выберите язык',
    profileAlertTitle: 'Личный профиль',
    profileAlertMsg: 'Управление профилем и учетными данными.',
    notifAlertTitle: 'Уведомления',
    notifAlertMsg: 'Настройки push-уведомлений обновлены.',
    signOutAlertTitle: 'Выход',
    signOutAlertMsg: 'Вы успешно вышли из системы.',
    courseDetails: 'Детали курса',
    viewLessons: 'Просмотр уроков и программы',
    maxScore: 'Макс. баллов',
    graded: 'Проверено',
    allGraded: 'Все проверены',
    publishToStudents: 'Опубликовать для студентов',
    createAssignment: 'Создать и опубликовать задание',
    title: 'Название',
    course: 'Курс',
  },
  uz: {
    dashboard: 'Boshqaruv paneli',
    courses: 'Kurslar',
    grading: 'Topshiriqlar va baholash',
    assignments: 'Topshiriqlar',
    settings: 'Sozlamalar',
    goodMorning: 'Xayrli tong,',
    adminOverview: 'Administrator boshqaruv markazi',
    teacherOverview: 'O\'qituvchi umumiy ko\'rinishi',
    assistantTeacherOverview: 'O\'qituvchi yordamchisi kabineti',
    studentOverview: 'Talaba umumiy ko\'rinishi',
    parentOverview: 'Ota-onalar nazorat portali',
    pendingTeacherActions: 'Kutilayotgan harakatlar',
    pendingAdminActions: 'Filial tizim ogohlantirishlari',
    pendingAssistantActions: 'Laboratoriya va testlarni baholash',
    parentUpdates: 'Farzandning o\'zlashtirish yangiliklari',
    recentActivity: 'So\'nggi faoliyat',
    activeClasses: 'Faol sinflar',
    toGrade: 'Tekshirilishi kerak',
    avgAttendance: 'O\'rtacha davomat',
    activeCourses: 'Faol kurslar',
    assignmentsDue: 'Topshirilishi kerak',
    completed: 'Bajarilgan',
    totalUsers: 'Jami foydalanuvchilar',
    systemHealth: 'Tizim holati',
    personalProfile: 'Shaxsiy profil',
    notifications: 'Bildirishnomalar va ogohlantirishlar',
    toggleTheme: 'Brend mavzusini o\'zgartirish',
    signOut: 'Tizimdan chiqish',
    activeRole: 'Ilovaning faol roli (5 ta rol):',
    adminMode: 'Admin',
    teacherMode: 'O\'qituvchi',
    assistantTeacherMode: 'Yordamchi',
    studentMode: 'Talaba',
    parentMode: 'Ota-ona',
    language: 'Tili / Language / Язык',
    selectLanguage: 'Tilni tanlang',
    profileAlertTitle: 'Shaxsiy profil',
    profileAlertMsg: 'Profilni boshqarish va ma\'lumotlar sozlamasi.',
    notifAlertTitle: 'Bildirishnomalar',
    notifAlertMsg: 'Bildirishnoma sozlamalari yangilandi.',
    signOutAlertTitle: 'Chiqish',
    signOutAlertMsg: 'Tizimdan muvaffaqiyatli chiqdingiz.',
    courseDetails: 'Kurs tafsilotlari',
    viewLessons: 'Darslar va dasturni ko\'rish',
    maxScore: 'Maks. ball',
    graded: 'Baholangan',
    allGraded: 'Barchasi baholangan',
    publishToStudents: 'Talabalarga e\'lon qilish',
    createAssignment: 'Topshiriq yaratish va e\'lon qilish',
    title: 'Sarlavha',
    course: 'Kurs',
  },
};

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: 'en',
  setLanguage: (language: Language) => set({ language }),
  t: (key: string) => {
    const lang = get().language;
    return translations[lang]?.[key] || translations.en[key] || key;
  },
}));
